FROM ghcr.io/neurodesk/itksnap_4.0.2:20240206

# ARG BUILD_DATE
# LABEL org.opencontainers.image.created=$BUILD_DATE
# LABEL org.opencontainers.image.authors="Neurodesk"
# LABEL org.opencontainers.image.url="https://www.neurodesk.org"
# LABEL org.opencontainers.image.documentation="https://www.neurodesk.org"
# LABEL org.opencontainers.image.source="git@github.com:NeuroDesk/neurocontainers.git"
# LABEL org.opencontainers.image.version="20240206"
# LABEL org.opencontainers.image.revision="GITHUB_SHA"
# LABEL org.opencontainers.image.vendor="Neurodesk"
# LABEL org.opencontainers.image.licenses="Open"
# LABEL org.opencontainers.image.ref.name="itksnap"
# LABEL org.opencontainers.image.title="itksnap"
# LABEL org.opencontainers.image.description="itksnap"
# LABEL org.opencontainers.image.base.digest=""
# LABEL org.opencontainers.image.base.name="itksnap"
