name: build-sif

on:
  workflow_dispatch:
    inputs:
      containername:
        description: 'containername'
        required: true
        type: string
      builddate:
        description: 'builddate'
        required: true
        type: string

jobs:
  build-sif:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.1
      - name: Run an apptainer container
        run: |
          CONTAINERNAME=${{ github.event.inputs.containername }}
          BUILDDATE=${{ github.event.inputs.builddate }}
          apptainer registry login --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
          apptainer pull docker://ghcr.io/neurodesk/${CONTAINERNAME}:${BUILDDATE}
          apptainer push ./${CONTAINERNAME}_${BUILDDATE}.sif oras://ghcr.io/${{ github.repository_owner }}/sif/${CONTAINERNAME}:${BUILDDATE}
          