name: build-sif

on:
  workflow_dispatch:

jobs:
  build-sif:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.1
      - name: Run an apptainer container
        run: |
          apptainer registry login --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
          apptainer pull docker://ghcr.io/neurodesk/itksnap_4.0.2:20240117
          apptainer push ./itksnap_4.0.2_20240117.sif oras://ghcr.io/${{ github.repository_owner }}/sif/itksnap_4.0.2:20240117
          